name: sachiel
description: A Trading Signals Platform for Cryptocurrency, Forex & More

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependency_overrides:
  fading_edge_scrollview: ^4.1.1

dependencies:
  flutter:
    sdk: flutter



  ####### ####### #######
  app_settings: ^5.1.1
  app_version_update: ^4.0.1
  ####### ####### #######



  ####### ####### #######
  back_button_interceptor: ^6.0.1

  blur: ^3.0.0
  ####### ####### #######



  ####### ####### #######
  connectivity_plus: ^5.0.2

  cloud_firestore: ^5.6.11
  cloud_functions: ^5.6.0

  cupertino_icons: ^1.0.5

  currency_text_input_formatter: ^2.1.7
  ####### ####### #######



  ####### ####### #######
  firebase_core: ^3.15.1
  firebase_app_check: ^0.3.2+9

  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.3.9

  firebase_auth: ^5.6.2

  firebase_remote_config: ^5.4.7
  firebase_messaging: ^15.2.9
  firebase_in_app_messaging: ^0.8.1+9

  flutter_html: ^3.0.0-beta.2

  flutter_phoenix: ^1.0.0
  flutter_slidable: ^2.0.0
  fluttertoast: ^8.0.9
  ####### ####### #######



  ####### ####### #######
  google_sign_in: ^6.2.1
  ####### ####### #######



  ####### ####### #######
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+1

  intl: ^0.17.0
  ####### ####### #######



  ####### ####### #######
  liquid_swipe: ^3.1.0
  loading_animation_widget:
    path: 'X:\Xlutter\Libraries\loading_animation_widget'
  local_auth: ^2.1.0
  ####### ####### #######



  ####### ####### #######
  marquee: ^2.2.3
  ####### ####### #######



  ####### ####### #######
  quick_actions: ^1.0.6
  ####### ####### #######



  ####### ####### #######
  screenshot: ^3.0.0
  share_plus: ^7.2.2
  status_bar_control:
    path: 'X:\Xlutter\Libraries\flutter_statusbar_control'
  ####### ####### #######



  ####### ####### #######
  url_launcher: ^6.2.5
  ####### ####### #######



  ####### ####### #######
  webview_flutter: ^4.7.0
  widget_mask: ^1.0.0+0
  ####### ####### #######

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/ubuntu.ttf
    - family: Handwriting
      fonts:
        - asset: fonts/waterfall.ttf
    - family: Electric
      fonts:
        - asset: fonts/electric.ttf