/*
 * Copyright © 2022 By Geeks Empire.
 *
 * Created by Elias Fazel
 * Last modified 8/24/22, 8:05 AM
 *
 * Licensed Under MIT License.
 * https://opensource.org/licenses/MIT
 */

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY93XIKH52_iWPGJXXp6goYmikHDJEuno',
    appId: '1:730794126051:android:23edcd1950bd5176ffb3d6',
    messagingSenderId: '730794126051',
    projectId: 'sachiel-s-signals',
    storageBucket: 'sachiel-s-signals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoZW3pkwG09Qm9B_Hh24SkBMPPjgy9O3I',
    appId: '1:730794126051:ios:a6332efe1e30714effb3d6',
    messagingSenderId: '730794126051',
    projectId: 'sachiel-s-signals',
    storageBucket: 'sachiel-s-signals.appspot.com',
    androidClientId: '730794126051-1krtbvboikgaq8g0dck413tpmkqjhl4n.apps.googleusercontent.com',
    iosClientId: '730794126051-i1djtkuqt12t2rci5b0lqiv3ttr9jv52.apps.googleusercontent.com',
    iosBundleId: 'co.geeksempire.sachiel.signals.sachiel',
  );
}
